### ISSUE TITLE
diskarbitrationd SIGKIL problem when trying to upgrade to Big Sur from Catalina

### ISSUE THREAD

**Issue by SeptemberHX** [jpuxdev/HP-Spectre-X360-13-Early-2019-Hackintosh#1]
Hi there, thanks for your hardworking 👍 

Last three days I tried to update to Big Sur with both your Clover EFI and my newly created Opencore EFI, but both of them met the problem shown below.

![image](https://user-images.githubusercontent.com/18042424/103439529-a13f5180-4c78-11eb-93ba-3694205db467.png)

After booting into macOS installer, the Apple logo shown for several seconds and it crashed. When I tried to do the fresh installation, it always crashed with 12 minutes remaining, and the same output shown.

Searched with Google, but no much progress on it. Any ideas ?

**Comment by jpransxdev** [comment]
Happy new year! I had the same problem and gave up, however it's likely that Big Sur would boot if there was a way to finish the installation but am not sure if updates would work. You can try cloning or installing bs directly onto an ssd through virtualbox/vmware (raw disk), but am not very familiar with vmware and virtual box, I think it should be doable tho. This problem actually started way back with BS beta 3, beta 2 installed with no problem.

**Comment by jpransxdev** [comment]
Read this https://www.reddit.com/r/hackintosh/comments/ju0ye0/updating_to_bigsur_sigkill_by_diskarbitrationd55/gcp9rn8/
The workaround seems to be creating a VM in VirtualBox and attaching the physical partition from hard disk to it and starting the Big Sur installation from there.

Let me know if you made any progress :)

**Comment by jpuxdev** [comment]
I may try it soon

**Comment by SeptemberHX** [comment]
I just installed Big Sur to physical partition instead of virtual one, and shutdown vm at the country selection page. But both Clover and Opencore failed to boot.

For clover, it shows:
> rooting from the live fs of a sealed volume is not allowed on a release build

Google told me setting SecureBootMode to disabled on Opencore, and I cannot find such a solution with Clover, and I cannot make any progress with Clover.

For Opencore, it successfully booted and the Apple icon and progress bar shown, however, it sucks at about 60% of the progress bar. It should show the language selection page then, but nothing happened.

tips: For installing to physical partition with vmplayer, just install vmware player, and use https://github.com/paolo-projects/unlocker/releases/tag/3.0.3 to patch it. Then create a vm with OS type: macOS 11.1 with virtual disk first. After that, do not launch the vm, at the configuration page of the newly created vm, remove the virtual disk, and create a new disk with SATA/physical partition. Then launch it.

For the bootable iso creation, please refer to https://blog.petehouston.com/download-and-convert-macos-mojave-installer-into-iso-file/

And my opencore is attached. [Opencore EFI.zip](https://github.com/jpuxdev/HP-Spectre-X360-13-Early-2019-Hackintosh/files/5759857/EFI.2.zip)

Highly recommend creating a new partition or plugging a new disk if you want to try it :)

**Comment by SeptemberHX** [comment]
Stucks here... There should be something on the screen after it, but nothing happened. External screen didn't work either.

Any ideas ?

![image](https://user-images.githubusercontent.com/18042424/103454537-2893d000-4d20-11eb-9319-ea0e9b770b60.png)

**Comment by jpransxdev** [comment]
Do you maybe want to try my current EFI folder? I updated to latest clover, kexts, and made some changes to config.

**Comment by jpransxdev** [comment]
One more thing, maybe try disabling applealc until you have completed the whole installation. I remember applealc causing some conflicts during install. And also disable/replace the io80211 wifi driver in my EFI, it is meant for Catalina.

**Comment by SeptemberHX** [comment]
I already removed io80211, and your new version efi still didn't work with the error: "rooting from the live fs of a sealed volume is not allowed on a release build".

After searching it on Google, I think it is impossible to boot the system that is installed by others ( by vmware, virtualbox, or a real macbook ) with Clover because of the secure boot on Apple.

And Opencore can disable `SecureBootMode` which allows us to boot the system without this error. So maybe currently only opencore have the possibility to boot big sur if we try to install big sur with vmware.

**Comment by jpransxdev** [comment]
Thanks, I will attempt installing it on an external ssd during the weekend (maybe even tomorrow if I have time), now I'm curious myself. I'm sure OpenCore devs will fix the disk arbitration sigkill bug eventually and then it will be likely fixed in clover as well since it's based on opencore. :)

**Comment by k2ok3i** [comment]
It will be solved by adding SSDT-PMC.aml.

**Comment by jpransxdev** [comment]
Thanks, SSDT-PMC and some quirks changes got me through the first two phases of installation. After that booting from the hidden preboot partition seems to be required, f3 in clover shows hidden entries. I reached big sur desktop succesfully

Will update my repo soon.

**Comment by SeptemberHX** [comment]
> Thanks, SSDT-PMC and some quirks changes got me through the first two phases of installation. After that booting from the hidden preboot partition seems to be required, f3 in clover shows hidden entries. I reached big sur desktop succesfully
> 
> Will update my repo soon.

What quirks should be changed? I still have the problem with ssdt-pmc

**Comment by jpransxdev** [comment]
The main one was disablevariablewrite, I updated this repo you can have a look what I changed in the config.

However f9 boot picker has stopped working twice requiring bios reflash wonder if this has anything to do with it.

Can you maybe try only disabling main quirk I mention And let me know, not sure if the other quirks needed to be changed!

**Comment by k2ok3i** [comment]
[EFI.zip](https://github.com/jpuxdev/HP-Spectre-X360-13-Early-2019-Hackintosh/files/5839689/EFI.zip)

I am using OpenCore and it can boot correctly from USB. However, I have a bug where I cannot boot from the EFI partition of the internal SSD. Do you know the solution?  Please try to use this.

**Comment by SeptemberHX** [comment]
> The main one was disablevariablewrite, I updated this repo you can have a look what I changed in the config.
> 
> However f9 boot picker has stopped working twice requiring bios reflash wonder if this has anything to do with it.
> 
> Can you maybe try only disabling main quirk I mention And let me know, not sure if the other quirks needed to be changed!

Not test whether all the changes in quirks are needed or not, but it did solve the diskarbitrationd problem.

I only tested with installing Big Sur to a new partition with usb installer, and it seems installation is successful after booting from the hidden preboot partition. However, error "rooting from the live fs of a sealed volume is not allowed on a release build" shows. Still have no idea why this happens even if I used the same EFI all the time.

For the missing boot picker with f9, it should be solved by reseting nvram (I used opencore -> reset nvram, and the problem is solved).

---------

Update: I finally upgraded to Big Sur sucessfully. With clover, I can only boot from the hidden preboot entry, which solved the 'rooting rrom the live of ....' problem.

Another problem is the screen refresh rate. According to easyres, no 60hz, and only 40hz now.

And now I cannot mount efi partition and other partitions on the internal disk anymore. Another problem is the AirportItlwm text. `com.apple.iokit.IO80211Family` and `com.apple.driver.corecapture` are needed. Now itlwm.text is used instead.

**Comment by SeptemberHX** [comment]
> [EFI.zip](https://github.com/jpuxdev/HP-Spectre-X360-13-Early-2019-Hackintosh/files/5839689/EFI.zip)
> 
> I am using OpenCore and it can boot correctly from USB. However, I have a bug where I cannot boot from the EFI partition of the internal SSD. Do you know the solution? Please try to use this.

Only test it with usb, and I even cannot boot from usb directly. But I successfully boot it by manually selecting the efi file with F9. Thus, I think the problem could be solved by manually creating an entry with easyuefi

**Comment by shakenfwz** [comment]
Try to replace OpenHfsPlus.efi with HfsPlus.efi
